namespace: wackopicko
output:
  file_path: ./Fluid-Attacks-Results.csv
  format: CSV
working_dir: .
language: EN
sast:
  include:
    - .
  exclude:
    - glob(**/test/**)
sca:
  include:
    - .
  exclude:
    - glob(**/test/**)
